spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-server:5432/interview
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
jwt:
  secret-key: 7cfkQM9kEaAs1E3WUA5tOA5lcsxcHVHTzpVZydTiMQpBwRuiB0O3

server:
  port: 8090